#!/data/data/com.termux/files/usr/bin/bash

shopt -s expand_aliases
alias ee='echo -e'
echo
ee "\e[93mThis script will install Apache Ant in Termux."
ee "\e[93mLibraries compiled by \e[32mHax4us\e[93m, script written by \e[32mHax4us \e[93mand \e[32mMasterDevX\e[93m."
echo
if [ -e $PREFIX/bin/ant ]
then
	ee "\e[32mAnt is already installed!"
	echo
	exit
else
	case `dpkg --print-architecture` in
	aarch64)
		archname="aarch64" ;;
	arm64)
		archname="aarch64" ;;
	armhf)
		archname="arm" ;;
	armv7l)
		archname="arm" ;;
	arm)
		archname="arm" ;;
	*)
		ee "\e[91mERROR: Unknown architecture."; echo; exit ;;
	esac
	ee "\e[32m[*] \e[34mDownloading Ant(~8Mb) for ${archname}..."
	wget https://github.com/Hax4us/java/releases/download/v8/jdk8_${archname}.tar.gz -q
	ee "\e[32m[*] \e[34mMoving Ant to system..."
	mv jdk8_${archname}.tar.gz $PREFIX/share
	ee "\e[32m[*] \e[34mExtracting Apache Ant..."
	cd $PREFIX/share
	tar -xhf ant_${archname}.tar.gz
	ee "\e[32m[*] \e[34mMoving Java wrapper scripts to bin..."
	mv bin/* $PREFIX/bin
	ee "\e[32m[*] \e[34mCleaning up temporary files..."
	rm -rf $HOME/installant
	rm -rf $PREFIX/share/ant_${archname}.tar.gz
	rm -rf $PREFIX/share/bin
	echo
	ee "\e[32mAnt was successfully installed!\e[39m"
	echo
fi
