#!/data/data/com.termux/files/usr/bin/bash

shopt -s expand_aliases
alias ee='echo -e'
echo
ee "\e[93mThis script will install Apache Ant in Termux."
ee "\e[93mLibraries compiled by \e[32mKangris\e[93m."
echo
if [ -e $PREFIX/bin/ant ]
then
	ee "\e[32mAnt is already installed!"
	echo
	exit
else
	
	ee "\e[32m[*] \e[34mDownloading Ant(~8Mb) for ${archname}..."
	wget https://github.com/kangris-sket/ant/releases/ant-1.9.14.tar.gz -q
	ee "\e[32m[*] \e[34mMoving Ant to system..."
	mv ant-1.9.14.tar.gz $PREFIX/share
	ee "\e[32m[*] \e[34mExtracting Apache Ant..."
	cd $PREFIX/share
	tar -xhf ant-1.9.14.tar.gz
	ee "\e[32m[*] \e[34mMoving Ant scripts to bin..."
	mv bin/* $PREFIX/bin
	ee "\e[32m[*] \e[34mCleaning up temporary files..."
	rm -rf $HOME/installant
	rm -rf $PREFIX/share/ant-1.9.14.tar.gz
	rm -rf $PREFIX/share/bin
	echo
	ee "\e[32mAnt was successfully installed!\e[39m"
	echo
fi
